# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['startprogram.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('dataentry.py', '.'),
        ('example.py', '.'),
        ('dataformulas.py', '.'),
        ('dataoutputgui.py', '.'),
        ('datacartcal.csv', '.'),
        ('datagameclass.csv', '.'),
        ('bcalcexticon.png', '.'),
        ('quail-silhouette.png', '.'),
        ('angles.py', '.'),
        ('atmosphere.py', '.'),
        ('ballistics.py', '.'),
        ('bdc.py', '.'),
        ('constants.py', '.'),
        ('dataholder.py', '.'),
        ('dataholder2.py', '.'),
        ('drag.py', '.'),
        ('holdover.py', '.'),
        ('points.py', '.'),
        ('utils.py', '.'),
        ('windage.py', '.'),
        ('screenshots', 'screenshots'),
    ],
    hiddenimports=['ttkbootstrap', 'matplotlib.backends.backend_tkagg'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludedimports=[],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='bcalcballistics',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
